### ISSUE TITLE
ID for <li> elements (drag and drop)

### ISSUE THREAD

**Issue by agatakk** [agatakk/ciaplist#2]
@Cmaiek 
Drag and drop nie działa ponieważ wykorzystuje metodę dataTransfer, która w tym wypadku wymaga, by każdy element, do którego przypisane są wydarzenia drag oraz drop posiadał unikalne ID.  Bez ustawienia LI na ID drag and drop nie zadziała.

UWAGA! 
W HTML może być tylko jedno unikalne ID na cały plik, nie można przypisać takiego samego ID do elementu LI oraz np. INPUT tylko dlatego, że są to dwa różne tagi.

**Comment by Cmaiek** [comment]
Dodałem do modelu mechanizm tworzenia unikalnej wartości "item_li_id", każdy element <li> w HTML otrzymuje unikalne id.
