### ISSUE TITLE
ID, FOR, DATA-KEY

### ISSUE THREAD

**Issue by agatakk** [agatakk/ciaplist#4]
Elo,
usystematyzuj proszę id, for oraz data-key dla elementów listy: 

- dla label atrybut for
- dla input - id
- dla li data-key

niech wszystkie te atrybuty dla poszczególnych elementów/tagów w kodzie HTML z listy będą takie same
np.:
```
` <li class="form__list-item" draggable="true" data-key="Tuńczyk" id="item_id_90"><input type="checkbox" checked name="ticker" value="90" id="Tuńczyk">
                <label for="Tuńczyk">Tuńczyk [3]</label>
            </li>
            
            
            
            <li class="form__list-item" draggable="true" data-key="tabletki do zmywarki" id="item_id_89"><input type="checkbox" checked name="ticker" value="89" id="tabletki do zmywarki">
                <label for="tabletki do zmywarki">Tabletki do zmywarki [1]</label>
            </li>`
```

**Comment by Cmaiek** [comment]
Będzie Pani zadowolona.

**Comment by Cmaiek** [comment]
Ogarnięte i już całkiem kozacko działa, tylko jest jeden problem: po syncowaniu items przeniesione na dół listy mają podkreślenie tylko na tekście, reszta buttonu ma stary kolor...

**Comment by Cmaiek** [comment]
Wszystko dopracowane zgodnie z ustaleniami, działa.
